site:
    title: Internet Computer 
    url: https://sdk.dfinity.org
    #start_page: home.adoc
content:
    sources:
    #- url: ./docs
      #branches: HEAD  
    - url: git@github.com:dfinity-lab/docs.git
      branches: 'master' 
ui:
  bundle:
    #url: ./ic-doc-ui/build/ui-bundle.zip
    url: https://github.com/dfinity-lab/antora-sdk/raw/master/build/ui-bundle.zip
    snapshot: true

  #supplemental_files: ./supplemental_ui

asciidoc:
  attributes:
    proglang: Motoko
    company-id: DFINITY
    toc: ~
    platform: Internet Computer platform
    IC: Internet Computer
    sdk-short-name: DFINITY Canister SDK
    sdk-long-name: DFINITY Canister Software Development Kit (SDK)
