[build]
base = ""
publish = "build/site"
command = "npm i @antora/cli @antora/site-generator-default && $(npm bin)/antora --fetch antora-playbook.yml"

# Rewrite to download.dfinity.systems for fetchings artifacts
[[redirects]]
from = "/install.sh"
to = "https://download.dfinity.systems/sdk/install.sh"
status = 302

# Rewrite to download.dfinity.systems for fetchings artifacts
[[redirects]]
from = "/manifest.json"
to = "https://download.dfinity.systems/sdk/manifest.json"
status = 302

# Rewrite to download.dfinity.systems for fetchings artifacts
[[redirects]]
from = "/downloads/*"
to = "https://download.dfinity.systems/sdk/:splat"
status = 302

# update base url to docs
[[redirects]]
from = "/"
to = "/docs/index.html"
status = 302
force = true

# update stale url to language guide to new page
[[redirects]]
from = "/language-guide/index.html"
to = "/docs/language-guide/motoko.html"
status = 302
force = true